import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastProvider } from '@/components/providers/toaster-provider'
import { ConfettiProvider } from '@/components/providers/confetti-provider'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ThemeProvider as StyledThemes } from 'styled-components'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <ThemeProvider
        attribute='class'
        defaultTheme='system'
        enableSystem
        disableTransitionOnChange
      >
        <body className={`${inter.className} scrollbar-thin hover:scrollbar-thumb-[#0075af] scrollbar-thumb-rounded scrollbar-thumb-[#76c8ff]  dark:scrollbar-thumb-[#0284C7]`}>
          <ConfettiProvider />
          <ToastProvider />
          {children}
        </body>
      </ThemeProvider>
    </html>
  )
}
